version: '3'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_nest
      MYSQL_USER: admin
      MYSQL_PASSWORD: Password123!
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3307:3306"
  
  nest:
    build:
      context: . # The Dockerfile is now in the root directory
    container_name: nest-api
    environment:
      DATABASE_HOST: mysql
      DATABASE_PORT: 3306
      DATABASE_USER: admin
      DATABASE_PASSWORD: Password123!
      DATABASE_NAME: test_nest
    volumes:
      - ./backend:/usr/src/app  # Mount backend source code to enable hot-reloading
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    command: ["./wait-for-it.sh", "mysql:3306", "--", "npm", "run", "start:prod"]  # Use 'start:dev' for Nodemon (development mode)
  
  react:
    build:
      context: .
    container_name: react-frontend
    volumes:
      - ./frontend:/usr/src/app  # Mount frontend source code to enable live updates
    ports:
      - "3001:80"  # Map port 80 inside the container to port 3001 on the host machine
    environment:
      - CHOKIDAR_USEPOLLING=true  # Enable polling for live reload in Docker

volumes:
  mysql-data:
